/* ============================================================
   Real restaurant data — popular Tokyo spots for visitors
   Sources: japan-guide.com, TripAdvisor, Tabelog
   ============================================================ */

const CATEGORIES = {
  sushi:        { label: "Sushi",          emoji: "🍣" },
  ramen:        { label: "Ramen",          emoji: "🍜" },
  izakaya:      { label: "Izakaya",        emoji: "🍢" },
  tempura:      { label: "Tempura",        emoji: "🍤" },
  wagyu:        { label: "Wagyu & Yakiniku", emoji: "🥩" },
  soba:         { label: "Soba",           emoji: "🍝" },
  kaiseki:      { label: "Kaiseki",        emoji: "🍁" },
  cafe:         { label: "Café & Sweets",  emoji: "🍵" },
  okonomiyaki:  { label: "Okonomiyaki",    emoji: "🥞" },
  udon:         { label: "Udon",           emoji: "🍲" },
  curry:        { label: "Japanese Curry", emoji: "🍛" },
};

const RESTAURANTS = [
  {
    id: 1,
    name: "Sushi Koshikawa",
    jp: "寿司 越川",
    category: "sushi",
    area: "Akasaka",
    price: 3,
    rating: 4.9,
    reviews: 541,
    emoji: "🍣",
    hue: 355,
    featured: true,
    tagline: "Intimate counter sushi in Akasaka, beloved by tuna lovers.",
    description:
      "A small, reservation-only sushi counter in Akasaka. The chef serves a single omakase course built around premium tuna, with each piece of nigiri shaped to order. The intimate setting — just a handful of counter seats — makes it a favorite among visitors seeking an authentic Edomae sushi experience.",
    dishes: ["Omakase course (tuna special)", "Bluefin tuna nigiri", "Seasonal fish selection"],
    tags: ["Reservation required", "Counter seats", "English menu"],
    address: "Akasaka, Minato-ku, Tokyo",
    station: "Akasaka Sta. · 3 min walk",
    seats: "Counter 8",
    reservation: "Required (1–2 weeks ahead)",
    hours: "17:00–22:00 · Closed Sundays",
    lunch: null,
    dinner: "¥15,000–¥25,000",
    priceNote: "Omakase from ¥15,000",
  },
  {
    id: 2,
    name: "Shinjuku Sushi Hatsume",
    jp: "新宿 鮨初め",
    category: "sushi",
    area: "Shinjuku",
    price: 3,
    rating: 4.9,
    reviews: 628,
    emoji: "🍣",
    hue: 205,
    tagline: "Creative sushi with grilled lobster and sea urchin rolls.",
    description:
      "A highly rated sushi restaurant near Nishishinjuku, known for its creative approach to Edomae sushi. The grilled lobster and sea urchin roll is a signature. The counter seats let you watch the chef work, and the atmosphere is welcoming to international visitors.",
    dishes: ["Grilled lobster & sea urchin roll", "Omakase course", "Seasonal nigiri"],
    tags: ["English menu", "Counter seats", "Reservation recommended"],
    address: "Nishishinjuku, Shinjuku-ku, Tokyo",
    station: "Nishishinjuku Sta. · 5 min walk",
    seats: "Counter 10 · Tables 4",
    reservation: "Recommended",
    hours: "17:00–23:00 · Closed Sundays",
    lunch: null,
    dinner: "¥12,000–¥20,000",
    priceNote: "Omakase from ¥12,000",
  },
  {
    id: 3,
    name: "Sushi Inase",
    jp: "寿司 稲瀬",
    category: "sushi",
    area: "Shibuya",
    price: 2,
    rating: 5.0,
    reviews: 203,
    emoji: "🍣",
    hue: 190,
    tagline: "Chef Toshiki's nigiri is a must-try in Shibuya.",
    description:
      "A compact sushi counter in Shibuya run by Chef Toshiki, who trained at some of Tokyo's top sushi restaurants. The nigiri is the star — each piece is carefully seasoned and served at the perfect temperature. A great spot for a high-quality sushi meal without the formality of a high-end counter.",
    dishes: ["Nigiri course", "Seasonal omakase", "Toro nigiri"],
    tags: ["English menu", "Counter seats", "Walk-in friendly"],
    address: "Shibuya, Shibuya-ku, Tokyo",
    station: "Shibuya Sta. · 5 min walk",
    seats: "Counter 8",
    reservation: "Walk-in",
    hours: "17:00–23:00 · Closed Wednesdays",
    lunch: null,
    dinner: "¥8,000–¥15,000",
    priceNote: "From ¥8,000",
  },
  {
    id: 4,
    name: "Ebisu Sushi Hatsume",
    jp: "えびす 鮨初め",
    category: "sushi",
    area: "Ebisu",
    price: 3,
    rating: 5.0,
    reviews: 168,
    emoji: "🍣",
    hue: 210,
    tagline: "Creative and delicious sushi in Ebisu.",
    description:
      "A creative sushi restaurant in Ebisu, known for its innovative approach to traditional nigiri. The omakase course is highly praised, and the atmosphere is relaxed and welcoming. A great choice for visitors who want high-quality sushi in a more casual setting than a formal counter.",
    dishes: ["Creative omakase", "Seasonal nigiri", "Signature rolls"],
    tags: ["English menu", "Reservation recommended", "Table seats"],
    address: "Ebisu, Shibuya-ku, Tokyo",
    station: "Ebisu Sta. · 3 min walk",
    seats: "Counter 6 · Tables 8",
    reservation: "Recommended",
    hours: "17:00–23:00 · Closed Mondays",
    lunch: null,
    dinner: "¥10,000–¥18,000",
    priceNote: "Omakase from ¥10,000",
  },
  {
    id: 5,
    name: "Ginza Yakiniku Salon de Aging Beef",
    jp: "銀座 焼肉サロン・ド・エイジングビーフ",
    category: "wagyu",
    area: "Ginza",
    price: 3,
    rating: 5.0,
    reviews: 108,
    emoji: "🥩",
    hue: 0,
    tagline: "Aging beef yakiniku in the heart of Ginza.",
    description:
      "A yakiniku restaurant in Ginza specializing in aged beef. The meat is carefully aged to enhance its flavor and tenderness, then grilled to perfection at your table. The salon-style interior is elegant yet relaxed, making it a popular choice for both special occasions and casual dinners.",
    dishes: ["Aging beef course", "Wagyu tongue", "Kalbi (short rib)"],
    tags: ["English menu", "Table seats", "Reservation recommended"],
    address: "Ginza, Chuo-ku, Tokyo",
    station: "Ginza Sta. · 3 min walk",
    seats: "Tables 20",
    reservation: "Recommended",
    hours: "17:00–23:00 · Open daily",
    lunch: null,
    dinner: "¥8,000–¥15,000",
    priceNote: "From ¥8,000 per person",
  },
  {
    id: 6,
    name: "Beef Professional Ginza",
    jp: "ビーフプロフェッショナル 銀座",
    category: "wagyu",
    area: "Ginza",
    price: 3,
    rating: 4.9,
    reviews: 114,
    emoji: "🥩",
    hue: 15,
    tagline: "Premium wagyu and cold noodles in Ginza.",
    description:
      "A yakiniku restaurant in Ginza known for its high-quality wagyu and excellent cold noodles served at the end of the meal. The meat is sourced from premium producers, and the grilling is done right at your table. A favorite among both locals and visitors.",
    dishes: ["Wagyu course", "Cold noodles", "Premium kalbi"],
    tags: ["English menu", "Table seats", "Reservation recommended"],
    address: "Ginza, Chuo-ku, Tokyo",
    station: "Ginza Sta. · 4 min walk",
    seats: "Tables 16",
    reservation: "Recommended",
    hours: "17:00–23:00 · Open daily",
    lunch: null,
    dinner: "¥7,000–¥14,000",
    priceNote: "From ¥7,000 per person",
  },
  {
    id: 7,
    name: "Kobegyu Sumibiyaki Steak Ginza Fun",
    jp: "神戸牛 炭火焼ステーキ 銀座ふぁん",
    category: "wagyu",
    area: "Ginza",
    price: 3,
    rating: 4.9,
    reviews: 106,
    emoji: "🥩",
    hue: 30,
    tagline: "Kobe beef charcoal-grilled steak in Ginza.",
    description:
      "A steakhouse in Ginza specializing in Kobe beef grilled over charcoal. The high heat seals in the juices, creating a perfectly cooked steak with a smoky aroma. The restaurant has a warm, inviting atmosphere and is a great choice for a special meal.",
    dishes: ["Kobe beef steak course", "Charcoal-grilled wagyu", "Seasonal vegetables"],
    tags: ["English menu", "Table seats", "Reservation recommended"],
    address: "Ginza, Chuo-ku, Tokyo",
    station: "Ginza Sta. · 5 min walk",
    seats: "Tables 18",
    reservation: "Recommended",
    hours: "17:00–23:00 · Open daily",
    lunch: null,
    dinner: "¥8,000–¥16,000",
    priceNote: "From ¥8,000 per person",
  },
  {
    id: 8,
    name: "Akita Beef Teppanyaki Ginza Gomei",
    jp: "秋田牛 鉄板焼 銀座ご明",
    category: "wagyu",
    area: "Ginza",
    price: 3,
    rating: 4.9,
    reviews: 161,
    emoji: "🥩",
    hue: 45,
    tagline: "Akita beef teppanyaki with fresh seafood in Ginza.",
    description:
      "A teppanyaki restaurant in Ginza where the chef grills premium Akita beef and fresh seafood on an iron griddle right in front of you. The combination of high-quality meat and skilled technique makes for a memorable dining experience. The restaurant has a refined, adult atmosphere.",
    dishes: ["Akita beef teppanyaki", "Fresh seafood grill", "Omakase course"],
    tags: ["English menu", "Counter seats", "Reservation recommended"],
    address: "Ginza, Chuo-ku, Tokyo",
    station: "Ginza Sta. · 2 min walk",
    seats: "Counter 10 · Tables 6",
    reservation: "Recommended",
    hours: "17:00–23:00 · Open daily",
    lunch: null,
    dinner: "¥10,000–¥20,000",
    priceNote: "From ¥10,000 per person",
  },
  {
    id: 9,
    name: "Waketokuyama",
    jp: "和慶徳山",
    category: "kaiseki",
    area: "Ningyocho",
    price: 3,
    rating: 4.8,
    reviews: 89,
    emoji: "🍁",
    hue: 10,
    tagline: "Seasonal kaiseki with grilled abalone and seaweed aroma.",
    description:
      "A Michelin-starred kaiseki restaurant where the menu changes approximately every two weeks to showcase seasonal ingredients at their peak. The signature dish — grilled abalone with seaweed aroma and rich liver sauce — is a masterpiece. The serene, traditional setting offers a true taste of Japanese haute cuisine.",
    dishes: ["Seasonal kaiseki course", "Grilled abalone with seaweed aroma", "Wagashi sweet"],
    tags: ["Reservation required", "Counter seats", "English menu", "Michelin 1 star"],
    address: "Ningyocho, Chuo-ku, Tokyo",
    station: "Ningyocho Sta. · 3 min walk",
    seats: "Counter 8 · Private 4",
    reservation: "Required (2–3 weeks ahead)",
    hours: "17:30–21:00 · Closed Sundays",
    lunch: null,
    dinner: "¥15,000–¥25,000",
    priceNote: "From ¥15,000",
  },
  {
    id: 10,
    name: "TEMPURA & WINE SHINO",
    jp: "天ぷら ワイン 志乃",
    category: "tempura",
    area: "Ginza",
    price: 3,
    rating: 4.7,
    reviews: 76,
    emoji: "🍤",
    hue: 50,
    tagline: "Elegant tempura paired with fine wine in Ginza.",
    description:
      "A hidden gem in Ginza where tempura is fried to a light, elegant texture using refined techniques. The thin, white batter minimizes oil aroma, letting the natural flavors of the ingredients shine. Champagne and Burgundy wines are carefully selected by the sommelier to pair with each dish.",
    dishes: ["Tempura course", "Seasonal vegetable tempura", "Wine pairing"],
    tags: ["Reservation recommended", "Counter seats", "Wine list", "English menu"],
    address: "Ginza, Chuo-ku, Tokyo",
    station: "Ginza Sta. · 4 min walk",
    seats: "Counter 10",
    reservation: "Recommended",
    hours: "17:30–21:30 · Closed Sundays",
    lunch: null,
    dinner: "¥12,000–¥20,000",
    priceNote: "From ¥12,000",
  },
  {
    id: 11,
    name: "Daikanyama Issai Kassai",
    jp: "代官山 彩彩",
    category: "izakaya",
    area: "Daikanyama",
    price: 2,
    rating: 4.7,
    reviews: 134,
    emoji: "🍢",
    hue: 25,
    tagline: "Charcoal-grilled dishes and clay-pot rice in Daikanyama.",
    description:
      "A stylish izakaya in Daikanyama run by a chef with 30 years of experience in Japanese cuisine. The charcoal-grilled meat dishes and clay-pot rice are standouts. The modern interior with dim lighting creates a sophisticated yet relaxed atmosphere — perfect for a night out in one of Tokyo's most charming neighborhoods.",
    dishes: ["Charcoal-grilled meat", "Clay-pot rice", "Seasonal appetizers"],
    tags: ["English menu", "Table seats", "Walk-in friendly"],
    address: "Daikanyama, Shibuya-ku, Tokyo",
    station: "Daikanyama Sta. · 2 min walk",
    seats: "Tables 24 · Counter 6",
    reservation: "Walk-in",
    hours: "17:00–23:30 · Open daily",
    lunch: null,
    dinner: "¥3,000–¥6,000",
    priceNote: "¥3,000–¥6,000 per person",
  },
  {
    id: 12,
    name: "Torinao",
    jp: "鳥直",
    category: "izakaya",
    area: "Shinjuku",
    price: 2,
    rating: 4.6,
    reviews: 98,
    emoji: "🍗",
    hue: 40,
    tagline: "Exquisite yakitori with Koshu Kenmidori chicken.",
    description:
      "A yakitori restaurant in Shinjuku specializing in Koshu Kenmidori chicken, grilled over Kishu Binchotan charcoal for a delightful aroma. The tender, fluffy tsukune (chicken meatball) is particularly popular. The owner carefully selects Japanese sake to pair with the skewers.",
    dishes: ["Yakitori assortment", "Tsukune (chicken meatball)", "Grilled chicken thigh"],
    tags: ["English menu", "Counter seats", "Sake list"],
    address: "Shinjuku, Shinjuku-ku, Tokyo",
    station: "Shinjuku Sta. · 5 min walk",
    seats: "Counter 12 · Tables 8",
    reservation: "Walk-in",
    hours: "17:00–23:00 · Open daily",
    lunch: null,
    dinner: "¥2,500–¥5,000",
    priceNote: "¥2,500–¥5,000 per person",
  },
  {
    id: 13,
    name: "Fry-ya",
    jp: "フライ家",
    category: "izakaya",
    area: "Shibuya",
    price: 2,
    rating: 4.6,
    reviews: 112,
    emoji: "🍤",
    hue: 35,
    tagline: "Exquisite tonkatsu with a Swiss-trained chef.",
    description:
      "A tonkatsu restaurant in Shibuya run by a chef with experience earning stars in both Switzerland and Japan. The remarkably light tonkatsu is a favorite among both Japanese diners and visitors. The 'small portions, many varieties' concept lets you sample a wide selection.",
    dishes: ["Tonkatsu set", "Small-portion tasting", "Seasonal fried dishes"],
    tags: ["English menu", "Table seats", "Walk-in friendly"],
    address: "Shibuya, Shibuya-ku, Tokyo",
    station: "Shibuya Sta. · 4 min walk",
    seats: "Tables 16",
    reservation: "Walk-in",
    hours: "11:30–14:00, 17:00–21:00 · Closed Tuesdays",
    lunch: "¥1,500–¥2,500",
    dinner: "¥2,500–¥4,000",
    priceNote: "From ¥1,500",
  },
  {
    id: 14,
    name: "Hikarimono",
    jp: "光もの",
    category: "sushi",
    area: "Tsukishima",
    price: 2,
    rating: 4.5,
    reviews: 67,
    emoji: "🐟",
    hue: 200,
    tagline: "Casual sushi with the famous Hikari-maki roll.",
    description:
      "A casual sushi restaurant in Tsukishima with a relaxed, everyday atmosphere. The signature Hikari-maki — featuring sardines, pickled plum, and bettarazuke (sweet pickled radish) — boasts unique flavors especially popular among international visitors. A great spot for affordable, high-quality sushi.",
    dishes: ["Hikari-maki roll", "Nigiri set", "Seasonal sashimi"],
    tags: ["English menu", "Table seats", "Budget-friendly"],
    address: "Tsukishima, Chuo-ku, Tokyo",
    station: "Tsukishima Sta. · 3 min walk",
    seats: "Tables 20 · Counter 8",
    reservation: "Walk-in",
    hours: "11:30–14:00, 17:00–21:00 · Closed Wednesdays",
    lunch: "¥1,000–¥2,000",
    dinner: "¥2,000–¥3,500",
    priceNote: "From ¥1,000",
  },
];

const FOOD_GUIDE = [
  { emoji: "🍣", hue: 355, title: "Sushi", blurb: "Vinegared rice with fresh seafood, from conveyor-belt chains to ¥20,000 counters. Nigiri is the classic single piece.", try: "Must-try: <b>otoro</b> (fatty tuna)" },
  { emoji: "🍜", hue: 28, title: "Ramen", blurb: "Wheat noodles in rich regional broths — tonkotsu (pork), shoyu (soy), miso. Slurping is a compliment.", try: "Must-try: <b>tonkotsu</b> with extra chashu" },
  { emoji: "🍤", hue: 45, title: "Tempura", blurb: "Seafood and vegetables in a light batter, fried to order. Eat with tentsuyu sauce and grated daikon.", try: "Must-try: <b>anago</b> (sea eel)" },
  { emoji: "🍢", hue: 25, title: "Izakaya", blurb: "Japan's pub culture: small shared plates, yakitori skewers and drinks. Order a few things and pass them around.", try: "Must-try: <b>yakitori</b> + cold sake" },
  { emoji: "🍁", hue: 10, title: "Kaiseki", blurb: "Multi-course haute cuisine that follows the seasons — tiny, beautiful dishes in a calm traditional room.", try: "Must-try: the <b>seasonal set menu</b>" },
  { emoji: "🥩", hue: 0, title: "Wagyu", blurb: "Intensely marbled Japanese beef, grilled at your table (yakiniku) or as sukiyaki. Look for A4/A5 grades.", try: "Must-try: <b>A5 tongue</b> at yakiniku" },
  { emoji: "🍝", hue: 90, title: "Soba & Udon", blurb: "Buckwheat soba (nutty, firm) and thick wheat udon (soft, comforting) — hot or cold by season.", try: "Must-try: cold <b>zaru soba</b> in summer" },
  { emoji: "🍵", hue: 140, title: "Matcha & Sweets", blurb: "Stone-ground green tea served traditionally or as a latte, paired with wagashi and parfaits.", try: "Must-try: <b>matcha parfait</b>" },
];
