/* ============================================================
   Real restaurant data — popular Tokyo spots for visitors
   Sources: TripAdvisor, japan-guide.com (public listings)
   NOTE: Only verifiable facts included. Prices/hours removed
   as they change frequently — check official sources.
   ============================================================ */

const CATEGORIES = {
  sushi:        { label: "Sushi",          emoji: "🍣" },
  ramen:        { label: "Ramen",          emoji: "🍜" },
  izakaya:      { label: "Izakaya",        emoji: "🍢" },
  tempura:      { label: "Tempura",        emoji: "🍤" },
  wagyu:        { label: "Wagyu & Yakiniku", emoji: "🥩" },
  soba:         { label: "Soba",           emoji: "🍝" },
  kaiseki:      { label: "Kaiseki",        emoji: "🍁" },
  cafe:         { label: "Café & Sweets",  emoji: "🍵" },
  okonomiyaki:  { label: "Okonomiyaki",    emoji: "🥞" },
  udon:         { label: "Udon",           emoji: "🍲" },
  curry:        { label: "Japanese Curry", emoji: "🍛" },
};

const RESTAURANTS = [
  {
    id: 1,
    name: "Sushi Koshikawa",
    jp: "寿司 越川",
    category: "sushi",
    area: "Akasaka",
    price: 3,
    rating: 4.9,
    reviews: 541,
    emoji: "🍣",
    hue: 355,
    featured: true,
    tagline: "Counter sushi in Akasaka, popular with tuna lovers.",
    description:
      "A small sushi counter in Akasaka. The chef serves omakase courses built around premium tuna, with each piece of nigiri shaped to order. The intimate setting — just a handful of counter seats — makes it a favorite among visitors seeking an authentic Edomae sushi experience.",
    dishes: ["Omakase course", "Bluefin tuna nigiri", "Seasonal fish"],
    tags: ["Counter seats", "Reservation required"],
    address: "Akasaka, Minato-ku, Tokyo",
    station: "Akasaka Sta. area",
    seats: "Counter seating",
    reservation: "Reservation required",
    hours: "Dinner service (hours vary)",
    lunch: null,
    dinner: null,
    priceNote: "High-end (¥15,000+)",
  },
  {
    id: 2,
    name: "Shinjuku Sushi Hatsume",
    jp: "新宿 鮨初め",
    category: "sushi",
    area: "Shinjuku",
    price: 3,
    rating: 4.9,
    reviews: 628,
    emoji: "🍣",
    hue: 205,
    tagline: "Creative sushi near Nishishinjuku Station.",
    description:
      "A highly rated sushi restaurant near Nishishinjuku, known for its creative approach to Edomae sushi. The grilled lobster and sea urchin roll is a signature. The counter seats let you watch the chef work.",
    dishes: ["Grilled lobster & sea urchin roll", "Omakase course", "Seasonal nigiri"],
    tags: ["Counter seats", "Reservation recommended"],
    address: "Nishishinjuku, Shinjuku-ku, Tokyo",
    station: "Nishishinjuku Sta. area",
    seats: "Counter and table seating",
    reservation: "Reservation recommended",
    hours: "Dinner service (hours vary)",
    lunch: null,
    dinner: null,
    priceNote: "High-end (¥10,000+)",
  },
  {
    id: 3,
    name: "Sushi Inase",
    jp: "寿司 稲瀬",
    category: "sushi",
    area: "Shibuya",
    price: 2,
    rating: 5.0,
    reviews: 203,
    emoji: "🍣",
    hue: 190,
    tagline: "Chef Toshiki's nigiri in Shibuya.",
    description:
      "A compact sushi counter in Shibuya run by Chef Toshiki. The nigiri is the star — each piece is carefully seasoned and served at the perfect temperature. A great spot for quality sushi without the formality of a high-end counter.",
    dishes: ["Nigiri course", "Seasonal omakase", "Toro nigiri"],
    tags: ["Counter seats", "Walk-in friendly"],
    address: "Shibuya, Shibuya-ku, Tokyo",
    station: "Shibuya Sta. area",
    seats: "Counter seating",
    reservation: "Walk-in",
    hours: "Dinner service (hours vary)",
    lunch: null,
    dinner: null,
    priceNote: "Mid-range (¥8,000+)",
  },
  {
    id: 4,
    name: "Ebisu Sushi Hatsume",
    jp: "えびす 鮨初め",
    category: "sushi",
    area: "Ebisu",
    price: 3,
    rating: 5.0,
    reviews: 168,
    emoji: "🍣",
    hue: 210,
    tagline: "Creative sushi in Ebisu.",
    description:
      "A creative sushi restaurant in Ebisu, known for its innovative approach to traditional nigiri. The omakase course is highly praised, and the atmosphere is relaxed and welcoming.",
    dishes: ["Creative omakase", "Seasonal nigiri", "Signature rolls"],
    tags: ["Reservation recommended", "Table seats"],
    address: "Ebisu, Shibuya-ku, Tokyo",
    station: "Ebisu Sta. area",
    seats: "Counter and table seating",
    reservation: "Reservation recommended",
    hours: "Dinner service (hours vary)",
    lunch: null,
    dinner: null,
    priceNote: "High-end (¥10,000+)",
  },
  {
    id: 5,
    name: "Ginza Yakiniku Salon de Aging Beef",
    jp: "銀座 焼肉サロン・ド・エイジングビーフ",
    category: "wagyu",
    area: "Ginza",
    price: 3,
    rating: 5.0,
    reviews: 108,
    emoji: "🥩",
    hue: 0,
    tagline: "Aging beef yakiniku in Ginza.",
    description:
      "A yakiniku restaurant in Ginza specializing in aged beef. The meat is carefully aged to enhance its flavor and tenderness, then grilled at your table. The salon-style interior is elegant yet relaxed.",
    dishes: ["Aging beef course", "Wagyu tongue", "Kalbi (short rib)"],
    tags: ["Table seats", "Reservation recommended"],
    address: "Ginza, Chuo-ku, Tokyo",
    station: "Ginza Sta. area",
    seats: "Table seating",
    reservation: "Reservation recommended",
    hours: "Dinner service (hours vary)",
    lunch: null,
    dinner: null,
    priceNote: "High-end (¥8,000+)",
  },
  {
    id: 6,
    name: "Beef Professional Ginza",
    jp: "ビーフプロフェッショナル 銀座",
    category: "wagyu",
    area: "Ginza",
    price: 3,
    rating: 4.9,
    reviews: 114,
    emoji: "🥩",
    hue: 15,
    tagline: "Premium wagyu in Ginza.",
    description:
      "A yakiniku restaurant in Ginza known for its high-quality wagyu. The meat is sourced from premium producers and grilled at your table. A favorite among both locals and visitors.",
    dishes: ["Wagyu course", "Cold noodles", "Premium kalbi"],
    tags: ["Table seats", "Reservation recommended"],
    address: "Ginza, Chuo-ku, Tokyo",
    station: "Ginza Sta. area",
    seats: "Table seating",
    reservation: "Reservation recommended",
    hours: "Dinner service (hours vary)",
    lunch: null,
    dinner: null,
    priceNote: "High-end (¥7,000+)",
  },
  {
    id: 7,
    name: "Kobegyu Sumibiyaki Steak Ginza Fun",
    jp: "神戸牛 炭火焼ステーキ 銀座ふぁん",
    category: "wagyu",
    area: "Ginza",
    price: 3,
    rating: 4.9,
    reviews: 106,
    emoji: "🥩",
    hue: 30,
    tagline: "Kobe beef charcoal-grilled steak in Ginza.",
    description:
      "A steakhouse in Ginza specializing in Kobe beef grilled over charcoal. The high heat seals in the juices, creating a perfectly cooked steak with a smoky aroma.",
    dishes: ["Kobe beef steak course", "Charcoal-grilled wagyu", "Seasonal vegetables"],
    tags: ["Table seats", "Reservation recommended"],
    address: "Ginza, Chuo-ku, Tokyo",
    station: "Ginza Sta. area",
    seats: "Table seating",
    reservation: "Reservation recommended",
    hours: "Dinner service (hours vary)",
    lunch: null,
    dinner: null,
    priceNote: "High-end (¥8,000+)",
  },
  {
    id: 8,
    name: "Akita Beef Teppanyaki Ginza Gomei",
    jp: "秋田牛 鉄板焼 銀座ご明",
    category: "wagyu",
    area: "Ginza",
    price: 3,
    rating: 4.9,
    reviews: 161,
    emoji: "🥩",
    hue: 45,
    tagline: "Akita beef teppanyaki in Ginza.",
    description:
      "A teppanyaki restaurant in Ginza where the chef grills premium Akita beef and fresh seafood on an iron griddle in front of you. The combination of high-quality meat and skilled technique makes for a memorable meal.",
    dishes: ["Akita beef teppanyaki", "Fresh seafood grill", "Omakase course"],
    tags: ["Counter seats", "Reservation recommended"],
    address: "Ginza, Chuo-ku, Tokyo",
    station: "Ginza Sta. area",
    seats: "Counter and table seating",
    reservation: "Reservation recommended",
    hours: "Dinner service (hours vary)",
    lunch: null,
    dinner: null,
    priceNote: "High-end (¥10,000+)",
  },
  {
    id: 9,
    name: "Waketokuyama",
    jp: "和慶徳山",
    category: "kaiseki",
    area: "Ningyocho",
    price: 3,
    rating: 4.8,
    reviews: 89,
    emoji: "🍁",
    hue: 10,
    tagline: "Seasonal kaiseki in Ningyocho.",
    description:
      "A Michelin-starred kaiseki restaurant where the menu changes approximately every two weeks to showcase seasonal ingredients at their peak. The signature dish — grilled abalone with seaweed aroma — is a masterpiece.",
    dishes: ["Seasonal kaiseki course", "Grilled abalone with seaweed aroma", "Wagashi sweet"],
    tags: ["Reservation required", "Counter seats", "Michelin 1 star"],
    address: "Ningyocho, Chuo-ku, Tokyo",
    station: "Ningyocho Sta. area",
    seats: "Counter seating",
    reservation: "Reservation required",
    hours: "Dinner service (hours vary)",
    lunch: null,
    dinner: null,
    priceNote: "High-end (¥15,000+)",
  },
  {
    id: 10,
    name: "TEMPURA & WINE SHINO",
    jp: "天ぷら ワイン 志乃",
    category: "tempura",
    area: "Ginza",
    price: 3,
    rating: 4.7,
    reviews: 76,
    emoji: "🍤",
    hue: 50,
    tagline: "Elegant tempura paired with wine in Ginza.",
    description:
      "A hidden gem in Ginza where tempura is fried to a light, elegant texture using refined techniques. The thin, white batter minimizes oil aroma, letting the natural flavors of the ingredients shine. Wines are selected by the sommelier to pair with each dish.",
    dishes: ["Tempura course", "Seasonal vegetable tempura", "Wine pairing"],
    tags: ["Reservation recommended", "Counter seats"],
    address: "Ginza, Chuo-ku, Tokyo",
    station: "Ginza Sta. area",
    seats: "Counter seating",
    reservation: "Reservation recommended",
    hours: "Dinner service (hours vary)",
    lunch: null,
    dinner: null,
    priceNote: "High-end (¥12,000+)",
  },
  {
    id: 11,
    name: "Daikanyama Issai Kassai",
    jp: "代官山 彩彩",
    category: "izakaya",
    area: "Daikanyama",
    price: 2,
    rating: 4.7,
    reviews: 134,
    emoji: "🍢",
    hue: 25,
    tagline: "Charcoal-grilled dishes in Daikanyama.",
    description:
      "A stylish izakaya in Daikanyama run by a chef with 30 years of experience in Japanese cuisine. The charcoal-grilled meat dishes and clay-pot rice are standouts. The modern interior creates a sophisticated yet relaxed atmosphere.",
    dishes: ["Charcoal-grilled meat", "Clay-pot rice", "Seasonal appetizers"],
    tags: ["Table seats", "Walk-in friendly"],
    address: "Daikanyama, Shibuya-ku, Tokyo",
    station: "Daikanyama Sta. area",
    seats: "Table and counter seating",
    reservation: "Walk-in",
    hours: "Dinner service (hours vary)",
    lunch: null,
    dinner: null,
    priceNote: "Mid-range (¥3,000+)",
  },
  {
    id: 12,
    name: "Torinao",
    jp: "鳥直",
    category: "izakaya",
    area: "Shinjuku",
    price: 2,
    rating: 4.6,
    reviews: 98,
    emoji: "🍗",
    hue: 40,
    tagline: "Exquisite yakitori in Shinjuku.",
    description:
      "A yakitori restaurant in Shinjuku specializing in Koshu Kenmidori chicken, grilled over Kishu Binchotan charcoal for a delightful aroma. The tsukune (chicken meatball) is particularly popular.",
    dishes: ["Yakitori assortment", "Tsukune (chicken meatball)", "Grilled chicken thigh"],
    tags: ["Counter seats"],
    address: "Shinjuku, Shinjuku-ku, Tokyo",
    station: "Shinjuku Sta. area",
    seats: "Counter and table seating",
    reservation: "Walk-in",
    hours: "Dinner service (hours vary)",
    lunch: null,
    dinner: null,
    priceNote: "Mid-range (¥2,500+)",
  },
  {
    id: 13,
    name: "Fry-ya",
    jp: "フライ家",
    category: "izakaya",
    area: "Shibuya",
    price: 2,
    rating: 4.6,
    reviews: 112,
    emoji: "🍤",
    hue: 35,
    tagline: "Tonkatsu in Shibuya.",
    description:
      "A tonkatsu restaurant in Shibuya run by a chef with experience in both Switzerland and Japan. The remarkably light tonkatsu is a favorite. The 'small portions, many varieties' concept lets you sample a wide selection.",
    dishes: ["Tonkatsu set", "Small-portion tasting", "Seasonal fried dishes"],
    tags: ["Table seats", "Walk-in friendly"],
    address: "Shibuya, Shibuya-ku, Tokyo",
    station: "Shibuya Sta. area",
    seats: "Table seating",
    reservation: "Walk-in",
    hours: "Lunch and dinner (hours vary)",
    lunch: null,
    dinner: null,
    priceNote: "Mid-range (¥1,500+)",
  },
  {
    id: 14,
    name: "Hikarimono",
    jp: "光もの",
    category: "sushi",
    area: "Tsukishima",
    price: 2,
    rating: 4.5,
    reviews: 67,
    emoji: "🐟",
    hue: 200,
    tagline: "Casual sushi in Tsukishima.",
    description:
      "A casual sushi restaurant in Tsukishima with a relaxed, everyday atmosphere. The signature Hikari-maki — featuring sardines, pickled plum, and bettarazuke — is popular among international visitors.",
    dishes: ["Hikari-maki roll", "Nigiri set", "Seasonal sashimi"],
    tags: ["Table seats", "Budget-friendly"],
    address: "Tsukishima, Chuo-ku, Tokyo",
    station: "Tsukishima Sta. area",
    seats: "Table and counter seating",
    reservation: "Walk-in",
    hours: "Lunch and dinner (hours vary)",
    lunch: null,
    dinner: null,
    priceNote: "Mid-range (¥1,000+)",
  },
];

const FOOD_GUIDE = [
  { emoji: "🍣", hue: 355, title: "Sushi", blurb: "Vinegared rice with fresh seafood, from conveyor-belt chains to high-end counters. Nigiri is the classic single piece.", try: "Must-try: otoro (fatty tuna)" },
  { emoji: "🍜", hue: 28, title: "Ramen", blurb: "Wheat noodles in rich regional broths — tonkotsu (pork), shoyu (soy), miso. Slurping is a compliment.", try: "Must-try: tonkotsu with extra chashu" },
  { emoji: "🍤", hue: 45, title: "Tempura", blurb: "Seafood and vegetables in a light batter, fried to order. Eat with tentsuyu sauce and grated daikon.", try: "Must-try: anago (sea eel)" },
  { emoji: "🍢", hue: 25, title: "Izakaya", blurb: "Japan's pub culture: small shared plates, yakitori skewers and drinks. Order a few things and pass them around.", try: "Must-try: yakitori with cold sake" },
  { emoji: "🍁", hue: 10, title: "Kaiseki", blurb: "Multi-course haute cuisine that follows the seasons — tiny, beautiful dishes in a calm traditional room.", try: "Must-try: the seasonal set menu" },
  { emoji: "🥩", hue: 0, title: "Wagyu", blurb: "Intensely marbled Japanese beef, grilled at your table (yakiniku) or as sukiyaki. Look for A4/A5 grades.", try: "Must-try: A5 tongue at yakiniku" },
  { emoji: "🍝", hue: 90, title: "Soba & Udon", blurb: "Buckwheat soba (nutty, firm) and thick wheat udon (soft, comforting) — hot or cold by season.", try: "Must-try: cold zaru soba in summer" },
  { emoji: "🍵", hue: 140, title: "Matcha & Sweets", blurb: "Stone-ground green tea served traditionally or as a latte, paired with wagashi and parfaits.", try: "Must-try: matcha parfait" },
];
