/* ============================================================
   Sample data — illustrative restaurants for the demo site.
   v2: adds station, seats, reservation, lunch/dinner prices.
   ============================================================ */

const CATEGORIES = {
  sushi:        { label: "Sushi",          emoji: "🍣" },
  ramen:        { label: "Ramen",          emoji: "🍜" },
  izakaya:      { label: "Izakaya",        emoji: "🍢" },
  tempura:      { label: "Tempura",        emoji: "🍤" },
  wagyu:        { label: "Wagyu & Yakiniku", emoji: "🥩" },
  soba:         { label: "Soba",           emoji: "🍝" },
  kaiseki:      { label: "Kaiseki",        emoji: "🍁" },
  cafe:         { label: "Café & Sweets",  emoji: "🍵" },
  okonomiyaki:  { label: "Okonomiyaki",    emoji: "🥞" },
  udon:         { label: "Udon",           emoji: "🍲" },
  curry:        { label: "Japanese Curry", emoji: "🍛" },
};

const RESTAURANTS = [
  {
    id: 1,
    name: "Sushi Kaze",
    jp: "寿司 風",
    category: "sushi",
    area: "Ginza",
    price: 3,
    rating: 4.9,
    reviews: 312,
    emoji: "🍣",
    hue: 355,
    featured: true,
    tagline: "A 10-seat omakase counter in the heart of Ginza.",
    description:
      "Chef Sato trained for 15 years under a two-star master before opening this tiny counter. Each of the 12 courses follows the season — winter anago, spring tai — and every guest gets a friendly English explanation of each piece.",
    dishes: ["Seasonal omakase (12 courses)", "Otoro nigiri", "Chawanmushi"],
    tags: ["English menu", "Counter seats", "Reservation recommended"],
    address: "Ginza 4-2-8, Chuo-ku, Tokyo (sample address)",
    station: "Ginza Sta. · 2 min walk",
    seats: "Counter 8",
    reservation: "Required (1–2 weeks ahead)",
    hours: "17:00–23:00 · Closed Sundays",
    lunch: null,
    dinner: "¥8,000–¥15,000",
    priceNote: "Omakase from ¥8,000",
  },
  {
    id: 2,
    name: "Uogashi Market",
    jp: "魚河岸",
    category: "sushi",
    area: "Tsukiji",
    price: 1,
    rating: 4.6,
    reviews: 587,
    emoji: "🐟",
    hue: 205,
    tagline: "Fresh, fast and friendly sushi near the old fish market.",
    description:
      "A cheerful no-frills sushi bar where the chef calls out the morning's catch in English. Set meals (teishoku) come with miso soup, pickles and rice — a great first sushi experience that won't break the bank.",
    dishes: ["Maguro teishoku", "Kaisendon (seafood bowl)", "Tamago nigiri"],
    tags: ["English menu", "Walk-in friendly", "Budget-friendly"],
    address: "Tsukiji 3-11-5, Chuo-ku, Tokyo (sample address)",
    station: "Tsukiji Sta. · 3 min walk",
    seats: "Counter 12 · Tables 6",
    reservation: "Walk-in",
    hours: "11:00–14:30, 17:00–21:00",
    lunch: "¥900–¥1,800",
    dinner: "¥1,500–¥3,000",
    priceNote: "Sets from ¥900",
  },
  {
    id: 3,
    name: "Menya Tokyo",
    jp: "麺屋 東京",
    category: "ramen",
    area: "Shinjuku",
    price: 1,
    rating: 4.7,
    reviews: 943,
    emoji: "🍜",
    hue: 28,
    tagline: "Rich tonkotsu ramen with a ticket-machine twist.",
    description:
      "Order by ticket machine (English buttons), take a counter seat, and watch the chefs work. The 12-hour pork broth is the star — creamy, not greasy. A photo menu on every table makes ordering effortless for first-timers.",
    dishes: ["Tonkotsu ramen", "Spicy miso ramen", "Extra chashu (¥200)"],
    tags: ["Picture menu", "Ticket machine", "Counter seats"],
    address: "Shinjuku 2-14-9, Shinjuku-ku, Tokyo (sample address)",
    station: "Shinjuku Sta. · 4 min walk",
    seats: "Counter 14",
    reservation: "Walk-in",
    hours: "11:00–24:00 · Open daily",
    lunch: "¥850–¥1,200",
    dinner: "¥850–¥1,400",
    priceNote: "From ¥850",
  },
  {
    id: 4,
    name: "Noodle Dojo",
    jp: "ヌードル 道場",
    category: "ramen",
    area: "Shibuya",
    price: 1,
    rating: 4.5,
    reviews: 276,
    emoji: "🍥",
    hue: 100,
    tagline: "Fully vegan ramen that meat-lovers also queue for.",
    description:
      "A plant-based ramen bar with a convincing soy-based 'chashu' and a rich mushroom-shoyu broth. The English-speaking staff can make any bowl gluten-free or nut-free on request — rare in the ramen world.",
    dishes: ["Vegan tantanmen", "Mushroom shoyu ramen", "Gyoza (vegan)"],
    tags: ["Vegetarian", "Vegan", "English menu", "Gluten-free option"],
    address: "Shibuya 1-18-3, Shibuya-ku, Tokyo (sample address)",
    station: "Shibuya Sta. · 6 min walk",
    seats: "Tables 16",
    reservation: "Walk-in",
    hours: "11:30–22:00 · Open daily",
    lunch: "¥980–¥1,400",
    dinner: "¥980–¥1,400",
    priceNote: "From ¥980",
  },
  {
    id: 5,
    name: "Izakaya Hana",
    jp: "居酒屋 花",
    category: "izakaya",
    area: "Asakusa",
    price: 2,
    rating: 4.6,
    reviews: 418,
    emoji: "🍢",
    hue: 25,
    tagline: "Old-school izakaya two minutes from Sensō-ji.",
    description:
      "Wooden beams, paper lanterns and 40 years of grilled goodness. Perfect after temple-hopping: try yakitori skewers, edamame and a cold sake. A big illustrated menu and patient staff make it very visitor-friendly.",
    dishes: ["Yakitori assortment", "Karaage (fried chicken)", "Dashimaki tamago"],
    tags: ["English menu", "Local atmosphere", "Sake list"],
    address: "Asakusa 2-7-4, Taito-ku, Tokyo (sample address)",
    station: "Asakusa Sta. · 2 min walk",
    seats: "Tables 20 · Tatami 4",
    reservation: "Walk-in (call for groups)",
    hours: "17:00–23:30 · Closed Wednesdays",
    lunch: null,
    dinner: "¥2,000–¥3,500",
    priceNote: "¥1,500–¥3,000 per person",
  },
  {
    id: 6,
    name: "Torikizoku",
    jp: "鳥貴族",
    category: "izakaya",
    area: "Shibuya",
    price: 1,
    rating: 4.4,
    reviews: 1021,
    emoji: "🍗",
    hue: 40,
    tagline: "Every skewer ¥130 — the famous yakitori chain.",
    description:
      "A lively national chain where every single item costs the same (¥130, tax included). Order by touchscreen at your seat — available in English — and watch the flames from the open grill. No reservations needed, ever.",
    dishes: ["Negima yakitori", "Tsukune (meatball)", "Cheese karaage"],
    tags: ["English menu", "Walk-in friendly", "Budget-friendly", "Late night"],
    address: "Shibuya 2-22-12, Shibuya-ku, Tokyo (sample address)",
    station: "Shibuya Sta. · 3 min walk",
    seats: "Tables 30",
    reservation: "Walk-in",
    hours: "17:00–05:00 · Open daily",
    lunch: null,
    dinner: "All items ¥130",
    priceNote: "All items ¥130",
  },
  {
    id: 7,
    name: "Tempura Ten",
    jp: "天",
    category: "tempura",
    area: "Ginza",
    price: 3,
    rating: 4.8,
    reviews: 195,
    emoji: "🍤",
    hue: 45,
    tagline: "Crisp seasonal tempura, served piece by piece.",
    description:
      "The chef fries each piece to order at a counter built around a single grill. Seasonal vegetables come from a market visit each morning, and the set lunch is one of Ginza's best values for a special-occasion feel.",
    dishes: ["Tempura teishoku (lunch)", "Anago (sea eel)", "Shiso maki"],
    tags: ["Counter seats", "Reservation recommended", "Lunch set"],
    address: "Ginza 5-3-2, Chuo-ku, Tokyo (sample address)",
    station: "Ginza Sta. · 3 min walk",
    seats: "Counter 10",
    reservation: "Recommended",
    hours: "Lunch 11:30–14:00 · Dinner 17:30–21:30",
    lunch: "¥3,000",
    dinner: "¥7,000–¥12,000",
    priceNote: "Lunch ¥3,000 · Dinner from ¥7,000",
  },
  {
    id: 8,
    name: "Yakiniku Masa",
    jp: "焼肉",
    category: "wagyu",
    area: "Shibuya",
    price: 3,
    rating: 4.7,
    reviews: 356,
    emoji: "🥩",
    hue: 0,
    tagline: "Grill A5 wagyu at your own table.",
    description:
      "Yakiniku (Korean-style grilled meat) at its finest: marbled A5 wagyu, premium short ribs and a grill built into every table. English picture menus and a 'grill-it-for-me' option for nervous first-timers.",
    dishes: ["A5 wagyu tongue", "Kalbi (short rib)", "Grilled garlic rice"],
    tags: ["English menu", "Group-friendly", "Private room"],
    address: "Shibuya 3-9-7, Shibuya-ku, Tokyo (sample address)",
    station: "Shibuya Sta. · 5 min walk",
    seats: "Tables 24 · Private 2",
    reservation: "Recommended",
    hours: "17:00–23:00 · Open daily",
    lunch: null,
    dinner: "¥4,000–¥8,000",
    priceNote: "From ¥4,000 per person",
  },
  {
    id: 9,
    name: "Soba Yamamoto",
    jp: "そば",
    category: "soba",
    area: "Kagurazaka",
    price: 2,
    rating: 4.6,
    reviews: 234,
    emoji: "🍝",
    hue: 90,
    tagline: "Hand-cut buckwheat noodles in a quiet backstreet.",
    description:
      "In chic Kagurazaka, this family shop mills its own buckwheat. Order kake soba (hot) in winter or zaru soba (cold with dipping sauce) in summer. The soba-yu noodle water at the end of the meal is a local ritual.",
    dishes: ["Zaru soba", "Tempura soba", "Matcha warabi mochi"],
    tags: ["English menu", "Quiet atmosphere", "Tatami seats"],
    address: "Kagurazaka 2-4-1, Shinjuku-ku, Tokyo (sample address)",
    station: "Kagurazaka Sta. · 2 min walk",
    seats: "Counter 6 · Tatami 3",
    reservation: "Walk-in",
    hours: "11:30–14:00, 17:30–20:30 · Closed Mondays",
    lunch: "¥1,100–¥1,800",
    dinner: "¥1,800–¥3,000",
    priceNote: "From ¥1,100",
  },
  {
    id: 10,
    name: "Kaiseki Momiji",
    jp: "懐石 紅葉",
    category: "kaiseki",
    area: "Akasaka",
    price: 3,
    rating: 4.9,
    reviews: 128,
    emoji: "🍁",
    hue: 10,
    tagline: "A seasons-on-a-plate kaiseki evening.",
    description:
      "Kaiseki is Japan's haute cuisine: a multi-course procession of tiny, perfect dishes that change with the calendar. English translations accompany every course, and the private room seats up to six for a truly special night.",
    dishes: ["Seasonal kaiseki (8 courses)", "Sakizuke appetizer", "Wagashi sweet"],
    tags: ["Reservation recommended", "Private room", "English menu", "Special occasion"],
    address: "Akasaka 3-12-6, Minato-ku, Tokyo (sample address)",
    station: "Akasaka-Mitsuke Sta. · 3 min walk",
    seats: "Counter 8 · Private 6",
    reservation: "Required",
    hours: "17:00–21:30 · Closed Sundays & holidays",
    lunch: null,
    dinner: "¥12,000–¥20,000",
    priceNote: "From ¥12,000",
  },
  {
    id: 11,
    name: "Matcha Moon",
    jp: "抹茶",
    category: "cafe",
    area: "Harajuku",
    price: 1,
    rating: 4.5,
    reviews: 689,
    emoji: "🍵",
    hue: 140,
    tagline: "Ceremonial-grade matcha and famous parfaits.",
    description:
      "A bright café serving stone-ground Uji matcha prepared the traditional way, plus towering parfaits with mochi, red bean and soft serve. Plenty of seating and free Wi-Fi — a perfect rest stop between Harajuku sights.",
    dishes: ["Matcha parfait", "Usucha (thin tea) set", "Matcha croissant"],
    tags: ["English menu", "Wi-Fi", "Vegetarian", "Great for breaks"],
    address: "Harajuku 6-4-15, Shibuya-ku, Tokyo (sample address)",
    station: "Harajuku Sta. · 2 min walk",
    seats: "Tables 28 · Wi-Fi",
    reservation: "Walk-in",
    hours: "10:00–20:00 · Open daily",
    lunch: "¥600–¥1,200",
    dinner: "¥600–¥1,200",
    priceNote: "From ¥600",
  },
  {
    id: 12,
    name: "Okonomi House",
    jp: "お好み",
    category: "okonomiyaki",
    area: "Akihabara",
    price: 2,
    rating: 4.4,
    reviews: 287,
    emoji: "🥞",
    hue: 30,
    tagline: "Savory pancakes you grill yourself — or we do it for you.",
    description:
      "Okonomiyaki ('grilled as you like it') is Japan's favorite comfort food. Mix your own batter on the hot plate with the staff's guidance, or choose 'oshobori' style and let the chef handle everything.",
    dishes: ["Classic pork okonomiyaki", "Cheese & mochi", "Monjayaki"],
    tags: ["English menu", "Group-friendly", "Interactive cooking"],
    address: "Akihabara 1-16-8, Chiyoda-ku, Tokyo (sample address)",
    station: "Akihabara Sta. · 4 min walk",
    seats: "Tables 18 · Grill seats",
    reservation: "Walk-in",
    hours: "11:00–23:00 · Open daily",
    lunch: "¥1,200–¥2,200",
    dinner: "¥1,200–¥2,200",
    priceNote: "From ¥1,200",
  },
  {
    id: 13,
    name: "Udon Shin",
    jp: "うどん 信",
    category: "udon",
    area: "Asakusa",
    price: 1,
    rating: 4.5,
    reviews: 342,
    emoji: "🍲",
    hue: 55,
    tagline: "Chewy hand-pulled udon in a tiny Asakusa shop.",
    description:
      "The noodles are pulled to order and you can watch through a glass window. Stand at the counter or sit at a low table; either way, the kitsune udon (sweet tofu) and cold bukkake are local favorites.",
    dishes: ["Kitsune udon", "Bukkake udon", "Tempura tendon"],
    tags: ["Walk-in friendly", "Budget-friendly", "Counter seats"],
    address: "Asakusa 1-22-3, Taito-ku, Tokyo (sample address)",
    station: "Asakusa Sta. · 5 min walk",
    seats: "Counter 10",
    reservation: "Walk-in",
    hours: "10:00–15:00 · Closed Tuesdays",
    lunch: "¥550–¥900",
    dinner: null,
    priceNote: "From ¥550",
  },
  {
    id: 14,
    name: "Tokyo Curry Club",
    jp: "カレー",
    category: "curry",
    area: "Shibuya",
    price: 1,
    rating: 4.3,
    reviews: 465,
    emoji: "🍛",
    hue: 18,
    tagline: "Japan's beloved comfort curry, done right.",
    description:
      "Japanese curry is thicker, sweeter and gentler than its South Asian cousins — a great intro for new palates. Choose your spice level (0 to 5) and pick a topping: tonkatsu, cheese or seasonal vegetables.",
    dishes: ["Chicken katsu curry", "Cheese curry", "Vegetable curry (vegan)"],
    tags: ["English menu", "Spice levels", "Vegetarian option"],
    address: "Shibuya 1-6-10, Shibuya-ku, Tokyo (sample address)",
    station: "Shibuya Sta. · 4 min walk",
    seats: "Tables 22",
    reservation: "Walk-in",
    hours: "11:00–22:00 · Open daily",
    lunch: "¥800–¥1,300",
    dinner: "¥800–¥1,300",
    priceNote: "From ¥800",
  },
];

const FOOD_GUIDE = [
  { emoji: "🍣", hue: 355, title: "Sushi", blurb: "Vinegared rice paired with fresh seafood — from conveyor-belt chains to ¥20,000 counters. Nigiri is the classic single piece.", try: "Must-try: <b>otoro</b> (fatty tuna)" },
  { emoji: "🍜", hue: 28, title: "Ramen", blurb: "Wheat noodles in rich regional broths — tonkotsu (pork), shoyu (soy), miso. Slurp loudly; it's a compliment.", try: "Must-try: <b>tonkotsu</b> with extra chashu" },
  { emoji: "🍤", hue: 45, title: "Tempura", blurb: "Seafood and vegetables in a feather-light batter, fried to order. Eat with tentsuyu dipping sauce and grated daikon.", try: "Must-try: <b>anago</b> (sea eel)" },
  { emoji: "🍢", hue: 25, title: "Izakaya", blurb: "Japan's pub culture: small shared plates, yakitori skewers and drinks. Order a few things and pass them around.", try: "Must-try: <b>yakitori</b> + cold sake" },
  { emoji: "🍁", hue: 10, title: "Kaiseki", blurb: "Multi-course haute cuisine that follows the seasons. Tiny, beautiful dishes served in a calm, traditional room.", try: "Must-try: the <b>seasonal set menu</b>" },
  { emoji: "🥩", hue: 0, title: "Wagyu", blurb: "Intensely marbled Japanese beef, grilled at your table (yakiniku) or as sukiyaki. Look for A4/A5 grades.", try: "Must-try: <b>A5 tongue</b> at yakiniku" },
  { emoji: "🍝", hue: 90, title: "Soba & Udon", blurb: "Buckwheat soba (nutty, firm) and thick wheat udon (soft, comforting) — hot or cold depending on the season.", try: "Must-try: cold <b>zaru soba</b> in summer" },
  { emoji: "🍵", hue: 140, title: "Matcha & Sweets", blurb: "Stone-ground green tea served in ceremonies or lattes, paired with wagashi sweets and anmitsu parfaits.", try: "Must-try: <b>matcha parfait</b>" },
];
